version: '3.8'
services:
  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: kinok0-flask-app
    networks:
      - emotion
    container_name: python-server
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production

networks:
  emotion:
    driver: bridge